name: gliner-api
services:
  gliner-api:
    image: ghcr.io/freinold/gliner-api:0.1.0-rc5
    ports:
      - "8080:8080" # API and Gradio frontend
      - "9090:9090" # Prometheus metrics
    stdin_open: true
    tty: true
    volumes:
      - "${HOME}/.cache/huggingface:/app/huggingface"
      - "./example_configs/general_onnx.yaml:/app/config.yaml:ro"
    environment:
      []
      # If you want to secure your API, set your key here
      # - GLINER_API_API_KEY=CHANGEME
