name: gliner-api
services:
  gliner-api:
    image: ghcr.io/freinold/gliner-api:latest@sha256:be8ebed0ccfd0c3ca0d69f8531dcc57854d72fd103252390e3b5b3be9ab100c0
    ## Alternatively, you can build the image locally: choose either the CPU or GPU Dockerfile
    # build:
    #   context: .
    #   dockerfile: cpu.Dockerfile
    #   dockerfile: gpu.Dockerfile
    ports:
      - "8080:8080" # API and Gradio frontend
      - "9090:9090" # Prometheus metrics
    stdin_open: true
    tty: true
    volumes:
      - "${HOME}/.cache/huggingface:/app/huggingface"
      - "./example_configs/general_onnx.yaml:/app/config.yaml:ro"
    environment:
      []
      # If you want to secure your deployment, set your API key here
      # - GLINER_API_API_KEY=CHANGEME
