services:
  gliner-api:
    build:
      context: .
      dockerfile: cpu.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "~/.cache/huggingface:/app/huggingface"
    stdin_open: true
    tty: true
