name: gliner-api
services:
  gliner-api:
    image: ghcr.io/freinold/gliner-api:0.1.0-rc4@sha256:b61c4f03952340a6cf1156f750f58829571d2e004c35f5714b76158434ed1013
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    volumes:
      - "${HOME}/.cache/huggingface:/app/huggingface"
      - "./example_configs/pii.yaml:/app/config.yaml:ro"
    environment:
      []
      # If you want to secure your API, set your key here
      # - GLINER_API_API_KEY=CHANGEME
