[project]
name = "gliner-api"
version = "0.3.7"
description = "Easily configurable API & frontend providing simple access to dynamic NER models"
readme = "README.md"
requires-python = "==3.14.5"
dependencies = [
    "fastapi[standard]==0.141.1",
    "gitpython==3.1.55",
    "huggingface-hub==1.28.0",
    "prometheus-client==0.26.0",
    "pydantic-settings==2.15.0",
    "uvicorn[standard]==0.52.4",
    "torch==2.13.0",
    "gliner[stanza]==0.2.28",
    "onnxruntime==1.29.0",
    "gradio==6.25.0",
    "httpx==0.28.1",
    "stamina==26.1.0",
]

[tool.uv.sources]
torch = [{ index = "pytorch-cpu" }]


[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[dependency-groups]
dev = ["ipykernel==7.3.0", "pre-commit==4.6.2", "ruff==0.16.4", "ty==0.0.74"]
